-- ready to test basic functions

diff --git a/trunk/do-update b/trunk/do-update
--- a/trunk/do-update
+++ b/trunk/do-update
@@ -44,8 +44,8 @@
 
 discover_version(){
 	# $1 package source name
-	# $2 on disk repository ($MIRRORLOCAL or $REPODST)
-	# $3 Release ($MIRRORDIST or $BASE_RELEASE)
+	# $2 on disk repository ($MIRRORLOCAL or $REPO_DEST)
+	# $3 Release ($MIRROR_DIST or $BASE_RELEASE)
 	# $4 sub-release (-security,-updates,-backports)
 
 	# Find "Package:", then find "Version:" and print the second field
@@ -59,7 +59,7 @@ get_binaries(){
   local src=$2
   
   # Upstream codename.
-  local ucodename=$(echo "$codename" | sed "s/$RELEASE/$MIRRORDIST/")  
+  local ucodename=$(echo "$codename" | sed "s/$RELEASE/$MIRROR_DIST/")  
 
   local binaries=$(awk -v pkg="$src" 'BEGIN { package_found = 0 }
 /^Package:/ { if ($2 == pkg) package_found = 1 }
@@ -83,18 +83,18 @@ get_section(){
   
   local section=""
   # Upstream codename.
-  local ucodename=$(echo "$codename" | sed "s/$RELEASE/$MIRRORDIST/")
+  local ucodename=$(echo "$codename" | sed "s/$RELEASE/$MIRROR_DIST/")
   
   if [ -n "$bin" ] ; then
     section=$(awk -v pkg="$bin" 'BEGIN { package_found = 0 }
 /^Package:/ { if ($2 == pkg) package_found = 1 }
 /^Section:/ { if (package_found == 1) { print $2; exit; } }' \
-"$MIRRORLOCAL"/dists/"$ucodename"/*/binary-"$GNS_HOST_ARCH"/Packages)
+"$MIRROR"/dists/"$ucodename"/*/binary-"$GNS_HOST_ARCH"/Packages)
     if [ -z "$section" ] ; then
       section=$(awk -v pkg="$bin" 'BEGIN { package_found = 0 }
 /^Package:/ { if ($2 == pkg) package_found = 1 }
 /^Section:/ { if (package_found == 1) { print $2; exit; } }' \
-"$MIRRORLOCAL"/dists/"$ucodename"/*/debian-installer/binary-"$GNS_HOST_ARCH"/Packages)
+"$MIRROR"/dists/"$ucodename"/*/debian-installer/binary-"$GNS_HOST_ARCH"/Packages)
     fi
     if [ -z "$section" ] ; then
       section=$(egrep -e "^$bin Section " override.bin | cut -d ' ' -f 3)
@@ -103,7 +103,7 @@ get_section(){
     section=$(awk -v pkg="$src" 'BEGIN { package_found = 0 }
 /^Package:/ { if ($2 == pkg) package_found = 1 }
 /^Section:/ { if (package_found == 1) { print $2; exit; } }' \
-"$MIRRORLOCAL"/dists/"$ucodename"/*/source/Sources)
+"$MIRROR"/dists/"$ucodename"/*/source/Sources)
     if [ -z "$section" ] ; then
       section=$(egrep -e "^$src Section " override.src | cut -d ' ' -f 3)
     fi
@@ -122,14 +122,14 @@ set_sections(){
   
   section=$(get_section "$codename" "$src")
   if [ -n "$section" ] ; then
-    echo "$src" Section "$section" >> "$REPODST"/conf/override."$codename".src
+    echo "$src" Section "$section" >> "$REPO_DEST"/conf/override."$codename".src
   fi
   
   binaries=$(get_binaries "$codename" "$src")
   for b in $binaries ; do
     section=$(get_section "$codename" "$src" "$b")
     if [ -n "$section" ] ; then
-      echo "$b" Section "$section" >> "$REPODST"/conf/override."$codename".bin
+      echo "$b" Section "$section" >> "$REPO_DEST"/conf/override."$codename".bin
     fi
   done
 }
@@ -142,12 +142,12 @@ remove_sourceless(){
 	# Binaries are debs or udebs. They either have the same name as the
 	# source or refer to the source.
 	# listfilter output = release|component|type: name version
-	local deb_versions=$(reprepro -Vb $REPODST -T deb listfilter $codename \
+	local deb_versions=$(reprepro -Vb $REPO_DEST -T deb listfilter $codename \
 "Source (==$pkg) | Package (==$pkg)" | cut -d " " -f 3 | sort | uniq)
-	local udeb_versions=$(reprepro -Vb $REPODST -T udeb listfilter $codename \
+	local udeb_versions=$(reprepro -Vb $REPO_DEST -T udeb listfilter $codename \
 "Source (==$pkg) | Package (==$pkg)" | cut -d " " -f 3 | sort | uniq)
 	local bin_versions=$(echo $deb_versions $udeb_versions | sort | uniq)
-	local src_versions=$(reprepro -Vb $REPODST -T dsc listfilter $codename \
+	local src_versions=$(reprepro -Vb $REPO_DEST -T dsc listfilter $codename \
 "Package (==$pkg)" | cut -d " " -f 3 | sort | uniq)
 	
 	# If a binary version has no source counterpart then delete all
@@ -161,9 +161,9 @@ remove_sourceless(){
 			fi
 		done
 		if [ -z "$found" ] ; then
-			reprepro -Vb $REPODST -T deb removefilter $codename \
+			reprepro -Vb $REPO_DEST -T deb removefilter $codename \
 "Version (==$bv), (Source (==$pkg) | Package (==$pkg) )"
-			reprepro -Vb $REPODST -T udeb removefilter $codename \
+			reprepro -Vb $REPO_DEST -T udeb removefilter $codename \
 "Version (==$bv), (Source (==$pkg) | Package (==$pkg) )"
 		fi
 	done
@@ -180,25 +180,25 @@ ensure_updated() {
   set_sections "$3" "$2"
 
 	# What version of this package do upstream have in our Sources file?
-	UPSTREAM_VERSION=$(discover_version $1 $MIRRORLOCAL $MIRRORDIST $distro_release) ||true
+	UPSTREAM_VERSION=$(discover_version $1 $MIRROR $MIRROR_DIST $distro_release) ||true
 
 	# What version of this package do we have in our Sources file?
-	OUR_VERSION=$(discover_version $2 $REPODST $BASE_RELEASE $distro_release |grep $DISTRONAME_L) ||true
+	OUR_VERSION=$(discover_version $2 $REPO_DEST $BASE_RELEASE $distro_release |grep $DIST_NAME_L) ||true
 
 	# If we are doing packages in -updates, and have a "non-existent" package, try -security
 	if [ -z "$OUR_VERSION" -a "$distro_release" == "-updates" ]; then
 		# Try to find a version in -security
-		OUR_VERSION=$(discover_version $2 $REPODST $BASE_RELEASE "-security" |grep $DISTRONAME_L) ||true
+		OUR_VERSION=$(discover_version $2 $REPO_DEST $BASE_RELEASE "-security" |grep $DIST_NAME_L) ||true
 
 		# If OUR_VERSION is no longer empty (eg, its in -security)
 		if [ -n $OUR_VERSION ]; then
 			# Remove the version from -updates, since its probably non-free upstream stuff
-			reprepro -Vb $REPODST removesrc $RELEASE$distro_release $1
+			reprepro -Vb $REPO_DEST removesrc $RELEASE$distro_release $1
 		fi
 	fi
 
-	# Find $DISTRONAME_L in $OUR_VERSION and delete everything to its left
-	CURRENT_VERSION=${OUR_VERSION#*$DISTRONAME_L}
+	# Find $DIST_NAME_L in $OUR_VERSION and delete everything to its left
+	CURRENT_VERSION=${OUR_VERSION#*$DIST_NAME_L}
 
 	if [ -n "$UPSTREAM_VERSION" ]; then # We have something to build from
 		# We haven't built yet, or are out of date
@@ -224,7 +224,7 @@ add_package() {
 	# $5 Build script
 
 	# Does this release of this distribution have this source package?
-	OUR_SOURCE=$(discover_version $1 $REPODST $BASE_RELEASE $distro_release |grep $DISTRONAME_L$2) ||true
+	OUR_SOURCE=$(discover_version $1 $REPO_DEST $BASE_RELEASE $distro_release |grep $DIST_NAME_L$2) ||true
 
 	if [ -z "$OUR_SOURCE" ]; then  # If we don't have this version, build it
 		# Build it
@@ -232,8 +232,8 @@ add_package() {
 			# Some things need to manipulate the repo itself
 			CHROOTDIR=$CHROOTDIR RELEASE=$4 VERSION="=$3" $5 || exit 1
 		else
-			chroot $CHROOTDIR bash -c "cd /builder && RELEASE=$4 VERSION='=$3' $CCACHE_PREFS $5" || exit 1
-			reprepro --ignore=missingfile -Vb $REPODST include $4 $CHROOTDIR/$WORKINGDIR/*.changes
+			chroot $CHROOTDIR bash -c "cd /forkmason && RELEASE=$4 VERSION='=$3' $CCACHE_PREFS $5" || exit 1
+			reprepro --ignore=missingfile -Vb $REPO_DEST include $4 $CHROOTDIR/$WORK_DIR/*.changes
 		fi
 	fi
 }
@@ -245,74 +245,90 @@ fi
 REDO=1
 while [ $REDO -eq 1 ]; do	# If versions in the config change, we could need to redo the lot
 	REDO=0
-	reprepro --noskipold -V -b $REPODST update || { echo "Repository update failed"; exit 1; }
+	reprepro --noskipold -V -b $REPO_DEST update || { echo "Repository update failed"; exit 1; }
 
 	# Non-Free, or no valid use.
 	for pkg in `cat packages-to-remove`; do
 		for postfix in '' -security $EXTRAS; do
-			reprepro -Vb $REPODST removesrc $RELEASE$postfix $pkg
+			reprepro -Vb $REPO_DEST removesrc $RELEASE$postfix $pkg
 		done
 	done
 
 	for distro_release in '' -security $EXTRAS; do
 		./update-chroot $distro_release
 
-		CHROOTDIR=$WORKINGDIR/$MIRRORDIST$distro_release-$GNS_HOST_ARCH
+		CHROOTDIR=$WORK_DIR/$MIRROR_DIST$distro_release-$GNS_HOST_ARCH
 
     # Regenerate overrides on every run.
     for type in src bin; do
-      OVERRIDE_FILE="$REPODST"/conf/override."$RELEASE""$distro_release"."$type"
+      OVERRIDE_FILE="$REPO_DEST"/conf/override."$RELEASE""$distro_release"."$type"
       rm -f "$OVERRIDE_FILE"
       touch "$OVERRIDE_FILE"
     done
 
-		# General
+		## -------
+		## General
+		## -------
+		# ----------------------------------
 		# ensure_updated srcname gnssrcname 
-		ensure_updated apt apt $RELEASE$distro_release ./gen-apt $APT_VERSION
-		ensure_updated cia-clients cia-clients $RELEASE$distro_release ./gen-cia-clients $CIA_SCRIPTS_VERSION
-		ensure_updated base-files base-files $RELEASE$distro_release ./gen-base-files $BASE_FILES_VERSION
-		ensure_updated example-content example-content $RELEASE$distro_release ./gen-example-content $EXAMPLE_CONTENT_VERSION
-		ensure_updated launchpad-integration launchpad-integration $RELEASE$distro_release ./gen-launchpad-integration $LAUNCHPAD_INTEGRATION_VERSION
-		ensure_updated linux linux $RELEASE$distro_release ./gen-linux $KERNEL_VERSION
-		ensure_updated linux-ubuntu-modules-$KERNEL_RELEASE linux-ubuntu-modules-$KERNEL_RELEASE $RELEASE$distro_release ./gen-linux-ubuntu-modules $LINUX_UBUNTU_MODULES_VERSION
-		ensure_updated module-init-tools module-init-tools $RELEASE$distro_release ./gen-module-init-tools $MODULE_INIT_TOOLS_VERSION
-		ensure_updated python-apt python-apt $RELEASE$distro_release ./gen-python-apt $PYTHON_APT_VERSION
-		ensure_updated texlive-base texlive-base $RELEASE$distro_release ./gen-texlive-base $TEXLIVE_BASE_VERSION
-		ensure_updated texlive-bin texlive-bin $RELEASE$distro_release ./gen-texlive-bin $TEXLIVE_BASE_VERSION
-		ensure_updated texlive-extra texlive-extra $RELEASE$distro_release ./gen-texlive-extra $TEXLIVE_EXTRA_VERSION
-		ensure_updated thunderbird thunderbird $RELEASE$distro_release ./gen-thunderbird $THUNDERBIRD_VERSION
-		ensure_updated ubiquity ubiquity $RELEASE$distro_release ./gen-ubiquity $UBIQUITY_VERSION
-		ensure_updated vlc vlc $RELEASE$distro_release ./gen-vlc $VLC_VERSION
+		# ----------------------------------
+#		ensure_updated apt apt $RELEASE$distro_release ./gen-apt $APT_VERSION
+#		ensure_updated cia-clients cia-clients $RELEASE$distro_release ./gen-cia-clients $CIA_SCRIPTS_VERSION
+#		ensure_updated base-files base-files $RELEASE$distro_release ./gen-base-files $BASE_FILES_VERSION
+#		ensure_updated example-content example-content $RELEASE$distro_release ./gen-example-content $EXAMPLE_CONTENT_VERSION
+#		ensure_updated launchpad-integration launchpad-integration $RELEASE$distro_release ./gen-launchpad-integration $LAUNCHPAD_INTEGRATION_VERSION
+#		ensure_updated linux linux $RELEASE$distro_release ./gen-linux $KERNEL_VERSION
+#		ensure_updated linux-ubuntu-modules-$KERNEL_RELEASE linux-ubuntu-modules-$KERNEL_RELEASE $RELEASE$distro_release ./gen-linux-ubuntu-modules $LINUX_UBUNTU_MODULES_VERSION
+#		ensure_updated module-init-tools module-init-tools $RELEASE$distro_release ./gen-module-init-tools $MODULE_INIT_TOOLS_VERSION
+#		ensure_updated python-apt python-apt $RELEASE$distro_release ./gen-python-apt $PYTHON_APT_VERSION
+#		ensure_updated texlive-base texlive-base $RELEASE$distro_release ./gen-texlive-base $TEXLIVE_BASE_VERSION
+#		ensure_updated texlive-bin texlive-bin $RELEASE$distro_release ./gen-texlive-bin $TEXLIVE_BASE_VERSION
+#		ensure_updated texlive-extra texlive-extra $RELEASE$distro_release ./gen-texlive-extra $TEXLIVE_EXTRA_VERSION
+#		ensure_updated thunderbird thunderbird $RELEASE$distro_release ./gen-thunderbird $THUNDERBIRD_VERSION
+#		ensure_updated ubiquity ubiquity $RELEASE$distro_release ./gen-ubiquity $UBIQUITY_VERSION
+#		ensure_updated vlc vlc $RELEASE$distro_release ./gen-vlc $VLC_VERSION
 
-		# Gnome
-		ensure_updated app-install-data-ubuntu app-install-data-ubuntu $RELEASE$distro_release ./gen-app-install-data-ubuntu $APP_INSTALL_DATA_UBUNTU_VERSION
-		ensure_updated epiphany-browser epiphany-browser $RELEASE$distro_release ./gen-epiphany-browser $EPIPHANY_BROWSER_VERSION
-		ensure_updated gnome-desktop gnome-desktop $RELEASE$distro_release ./gen-gnome-desktop $GNOME_DESKTOP_VERSION
-		ensure_updated gnome-panel gnome-panel $RELEASE$distro_release ./gen-gnome-panel $GNOME_PANEL_VERSION
-		ensure_updated human-icon-theme human-icon-theme $RELEASE$distro_release ./gen-human-icon-theme $HUMAN_ICON_THEME_VERSION
-		ensure_updated ubuntu-artwork $DISTRONAME_L-artwork $RELEASE$distro_release ./gen-artwork $ARTWORK_VERSION
-		ensure_updated ubuntu-meta $DISTRONAME_L-meta $RELEASE$distro_release ./gen-meta $META_VERSION
-		ensure_updated yelp yelp $RELEASE$distro_release ./gen-yelp $YELP_VERSION
+		## ------
+		## Gnome
+		## ------
+		# ----------------------------------
+		# ensure_updated srcname gnssrcname 
+		# ----------------------------------
+#		ensure_updated app-install-data-ubuntu app-install-data-ubuntu $RELEASE$distro_release ./gen-app-install-data-ubuntu $APP_INSTALL_DATA_UBUNTU_VERSION
+#		ensure_updated epiphany-browser epiphany-browser $RELEASE$distro_release ./gen-epiphany-browser $EPIPHANY_BROWSER_VERSION
+#		ensure_updated gnome-desktop gnome-desktop $RELEASE$distro_release ./gen-gnome-desktop $GNOME_DESKTOP_VERSION
+#		ensure_updated gnome-panel gnome-panel $RELEASE$distro_release ./gen-gnome-panel $GNOME_PANEL_VERSION
+#		ensure_updated human-icon-theme human-icon-theme $RELEASE$distro_release ./gen-human-icon-theme $HUMAN_ICON_THEME_VERSION
+#		ensure_updated ubuntu-artwork $DIST_NAME_L-artwork $RELEASE$distro_release ./gen-artwork $ARTWORK_VERSION
+#		ensure_updated ubuntu-meta $DIST_NAME_L-meta $RELEASE$distro_release ./gen-meta $META_VERSION
+#		ensure_updated yelp yelp $RELEASE$distro_release ./gen-yelp $YELP_VERSION
 
-		# KDE
-		# ensure_updated kubuntu-default-settings k$DISTRONAME_L-default-settings $RELEASE$distro_release ./gen-kdefault-settings $KDEFAULT_SETTINGS_VERSION
-		# ensure_updated kubuntu-meta k$DISTRONAME_L-desktop $RELEASE$distro_release ./gen-kmeta $KMETA_VERSION
+		## ----
+		## KDE
+		## ----
+		# ----------------------------------
+		# ensure_updated srcname gnssrcname 
+		# ----------------------------------
+#		 ensure_updated kubuntu-default-settings k$DIST_NAME_L-default-settings $RELEASE$distro_release ./gen-kdefault-settings $KDEFAULT_SETTINGS_VERSION
+#		 ensure_updated kubuntu-meta k$DIST_NAME_L-desktop $RELEASE$distro_release ./gen-kmeta $KMETA_VERSION
 
+		# ----------------------
 		# User-defined packages
+		# ----------------------
 		if [ -d packages/$RELEASE$distro_release ]; then
 			for PKG in packages/$RELEASE$distro_release/*; do
 				PKGNAME=${PKG##*/}
 				PKG_VERSION=$(sed '1{s/.*(\(.*\)).*/\1/;q}' $PKG/debian/changelog)
-				REPO_VERSION=$(reprepro -b $REPODST -T deb list $RELEASE$distro_release $PKGNAME | cut -f 3 -d ' ' |head -n 1 ) || true
+				REPO_VERSION=$(reprepro -b $REPO_DEST -T deb list $RELEASE$distro_release $PKGNAME | cut -f 3 -d ' ' |head -n 1 ) || true
 				if [ -z "$REPO_VERSION" ] || dpkg --compare-versions $PKG_VERSION gt $REPO_VERSION; then
-					rm -rf $CHROOTDIR/$WORKINGDIR
-					mkdir -p $CHROOTDIR/$WORKINGDIR
-					cp -r $PKG $CHROOTDIR/$WORKINGDIR
+					rm -rf $CHROOTDIR/$WORK_DIR
+					mkdir -p $CHROOTDIR/$WORK_DIR
+					cp -r $PKG $CHROOTDIR/$WORK_DIR
 					# What are the packages build-deps?
-					PKG_BUILD_DEPS=$(chroot $CHROOTDIR bash -c "cd $WORKINGDIR/$PKGNAME && dpkg-checkbuilddeps 2>&1 |sed -e 's/ *([^)]*)//g' | cut -d ' ' -f 5-")
-					chroot $CHROOTDIR bash -c "cd $WORKINGDIR/$PKGNAME && apt-get -y install $PKG_BUILD_DEPS"
-					chroot $CHROOTDIR bash -c "cd $WORKINGDIR/$PKGNAME && $CCACHE_PREFS dpkg-buildpackage $DPKGOPTS"
-					reprepro -Vb $REPODST include $RELEASE$distro_release $CHROOTDIR/$WORKINGDIR/*.changes
+					PKG_BUILD_DEPS=$(chroot $CHROOTDIR bash -c "cd $WORK_DIR/$PKGNAME && dpkg-checkbuilddeps 2>&1 |sed -e 's/ *([^)]*)//g' | cut -d ' ' -f 5-")
+					chroot $CHROOTDIR bash -c "cd $WORK_DIR/$PKGNAME && apt-get -y install $PKG_BUILD_DEPS"
+					chroot $CHROOTDIR bash -c "cd $WORK_DIR/$PKGNAME && $CCACHE_PREFS dpkg-buildpackage $DPKGOPTS"
+					reprepro -Vb $REPO_DEST include $RELEASE$distro_release $CHROOTDIR/$WORK_DIR/*.changes
 				fi
 			done
 		fi
@@ -320,12 +336,17 @@ while [ $REDO -eq 1 ]; do	# If versions in the config change, we could need to r
 	done
 done
 
+# --------------------
 # Extra meta packages
+# --------------------
 ./gen-emeta
 
-# Unset BUILDARCH so it won't contaminate future runs
-unset BUILDARCH
-unset MAINTINFO
+# --------------------------------
+# Unset BUILD_ARCH so it 
+# won't contaminate future runs
+# --------------------------------
+unset BUILD_ARCH
+unset MAINT_INFO
 unset DPKGOPTS
 
 echo "do-update completed"
